title: I am ACM
description: BLOG DESCRIPTION
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea
  - Makefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

imgpath: /assets/img

collections:
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
